const eventData={
  hackathon:{code:'VX-01',title:'48H Hack Protocol',category:'Coding',image:'images/events/hackathon.webp',team:'2–4 members',duration:'48 hours',venue:'Innovation Lab',slot:'Day 01 · 11:00',price:'₹799',summary:'Build and pitch a working solution to a real problem under a relentless clock.',description:'Teams move from problem discovery to a tested prototype and live pitch. Mentors support product thinking, engineering decisions and storytelling.',skills:['Full-stack','AI','Product'],takeaways:['Problem statements revealed at kickoff','Three mentor checkpoints','Prototype, repository and pitch deck required','Judged on impact, execution and clarity']},
  robotics:{code:'VX-02',title:'Autonomous Arena',category:'Robotics',image:'images/events/robotics.webp',team:'2–4 members',duration:'4 hours',venue:'Quadrangle',slot:'Day 01 · 14:00',price:'₹599',summary:'Engineer a machine that can read the arena, decide fast and move with precision.',description:'Design an autonomous robot for a staged navigation challenge combining line tracking, obstacles and object placement.',skills:['Sensors','Control','Hardware'],takeaways:['Bring your own assembled robot','Arena dimensions shared before the event','Multiple timed qualification rounds','Safety inspection is mandatory']},
  ideathon:{code:'VX-03',title:'Zero-to-One Ideathon',category:'Innovation',image:'images/events/ideathon.webp',team:'1–3 members',duration:'6 hours',venue:'Seminar Hall',slot:'Day 02 · 13:00',price:'₹299',summary:'Find the sharpest problem in the room and turn it into a credible venture story.',description:'A rapid innovation sprint connecting user pain, technology feasibility and a viable path to impact.',skills:['Strategy','Pitching','Research'],takeaways:['Themes span climate, health and access','Five-minute pitch plus Q&A','Evidence matters more than slide polish','Top concepts receive mentor feedback']},
  cyber:{code:'VX-04',title:'Cipher Siege',category:'Cyber',image:'images/events/cyber.webp',team:'1–2 members',duration:'5 hours',venue:'Network Lab',slot:'Day 02 · 10:30',price:'₹399',summary:'Trace the breach, break the cipher and capture every flag before the network closes.',description:'A beginner-friendly capture-the-flag competition covering web exploitation, cryptography, OSINT and digital forensics.',skills:['Web','Crypto','Forensics'],takeaways:['Isolated legal practice environment','Difficulty rises across five zones','Hints trade against final points','Bring a laptop with Linux support']},
  design:{code:'VX-05',title:'Pixel Craft X',category:'Design',image:'images/events/design.webp',team:'1–2 members',duration:'4 hours',venue:'Design Studio',slot:'Day 01 · 11:00',price:'₹249',summary:'Turn an ordinary brief into a digital experience people remember and want to use.',description:'A product-design challenge focused on user journeys, interface systems and the quality of the final story—not just the hero screen.',skills:['UI/UX','Systems','Story'],takeaways:['Brief and brand kit revealed onsite','Wireframes and high-fidelity screens','Accessibility is part of judging','Clickable prototype recommended']},
  gaming:{code:'VX-06',title:'Neon Circuit',category:'Gaming',image:'images/events/gaming.webp',team:'1–5 members',duration:'League format',venue:'Gaming Arena',slot:'Day 02 · 10:00',price:'₹499',summary:'Enter a tournament experience built for clean competition, sharp calls and clutch plays.',description:'A multi-title competitive gaming arena with structured brackets, referee oversight and dedicated warm-up slots.',skills:['Valorant','EA FC','Strategy'],takeaways:['Separate rules for every title','Valid student ID required','Anti-cheat checks before play','Fixtures published after check-in']},
  drone:{code:'VX-07',title:'Drone Vector',category:'Robotics',image:'images/events/drone.webp',team:'2–3 members',duration:'3 hours',venue:'Open Grounds',slot:'Day 02 · 09:00',price:'₹699',summary:'Navigate a precision flight course where every gate, turn and second counts.',description:'Pilots compete across technical flight stages that test control, speed, spatial awareness and safe recovery.',skills:['Piloting','Build','Precision'],takeaways:['Practice slot before qualification','Prop guards are compulsory','Battery safety rules apply','Fastest clean run wins']},
  data:{code:'VX-08',title:'Data After Dark',category:'Coding',image:'images/events/data.webp',team:'1–3 members',duration:'8 hours',venue:'AI Lab',slot:'Day 02 · 09:30',price:'₹349',summary:'Clean a chaotic dataset, find the signal and make a model decision-makers can trust.',description:'A practical data challenge where analysis quality, explainability and business interpretation matter as much as leaderboard score.',skills:['Python','ML','Insights'],takeaways:['Dataset released at kickoff','External pretrained models limited','Notebook and summary dashboard required','Judged on rigor and explainability']}
};
const id=new URLSearchParams(location.search).get('event'),event=eventData[id],main=document.querySelector('#event-page-main');
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
if(!event){document.title='Event not found // VertechX';main.innerHTML='<section class="event-not-found"><p class="kicker">SIGNAL LOST</p><h1>Event not found.</h1><a class="button button-primary" href="index.html#events">Return to events</a></section>'}else{
  document.title=`${event.title} // VertechX NEXT`;
  main.innerHTML=`<section class="event-detail-hero"><img src="${event.image}" alt="${event.title} competition"><div class="event-detail-overlay"><span>${event.code} / ${event.category.toUpperCase()}</span><h1>${event.title}</h1><p>${event.summary}</p><div class="event-detail-actions"><button class="button button-primary" id="event-plan-toggle" type="button"></button><a class="button" href="index.html?register=${id}#events">Register preview ↗</a></div></div></section><section class="event-detail-content"><div><p class="kicker">THE MISSION</p><h2>What you will build,<br><em>prove and present.</em></h2><p class="event-detail-description">${event.description}</p><div class="event-rule-grid">${event.takeaways.map((item,index)=>`<article><span>0${index+1}</span><p>${item}</p></article>`).join('')}</div></div><aside><dl><div><dt>SCHEDULE</dt><dd>${event.slot}</dd></div><div><dt>VENUE</dt><dd>${event.venue}</dd></div><div><dt>TEAM</dt><dd>${event.team}</dd></div><div><dt>DURATION</dt><dd>${event.duration}</dd></div><div><dt>ENTRY</dt><dd>${event.price} / team</dd></div></dl><div class="event-detail-skills">${event.skills.map(skill=>`<span>${skill}</span>`).join('')}</div><small>Concept timetable · verify official dates before attending.</small></aside></section>`;
  const plan=new Set(JSON.parse(localStorage.getItem('vx-plan')||'[]')),button=document.querySelector('#event-plan-toggle');const sync=()=>button.textContent=plan.has(id)?'✓ In my plan':'+ Add to my plan';sync();button.addEventListener('click',()=>{plan.has(id)?plan.delete(id):plan.add(id);localStorage.setItem('vx-plan',JSON.stringify([...plan]));sync();const toast=document.querySelector('#toast');toast.textContent=plan.has(id)?'Added to your festival plan':'Removed from your festival plan';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});
}
